# Generated by Django 3.1.5 on 2021-02-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Contries'},
        ),
    ]
